server:
  port: 8082



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_crud?characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: zdy110629
    driver-class-name: com.mysql.jdbc.Driver



#mybatis:
#  configuration.mapUnderscoreToCamelCase: true





